version: '3.4'
services:
  mizubo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: redis://redis:6379
    command: ["./bin/hubot", "--adapter", "slack"]
    stdin_open: true
    tty: true
    volumes:
      - ./:/hubot
